export const LATEST_BOOKS_REQUEST = "LATEST_BOOKS_REQUEST"
export const LATEST_BOOKS_SUCESS = "LATEST_BOOKS_SUCESS"
export const LATEST_BOOKS_FAIL = "LATEST_BOOKS_FAIL"

export const ALL_BOOKS_REQUEST = "ALL_BOOKS_REQUEST"
export const ALL_BOOKS_SUCESS = "ALL_BOOKS_SUCESS"
export const ALL_BOOKS_FAIL = "LATEST_BOOKS_FAIL"